version: "3.9"

services:
  chat-bot:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "node-chatbot"
    init: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGO_URL=${MONGO_URL}
    restart: unless-stopped

  db:
    image: mongo:8-noble
    ports:
      - "27018:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
