version: "3.9"

services:
  chat-bot:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "node-chatbot"
    init: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGO_URL=${MONGO_URL}
    restart: unless-stopped
