version: "3.9"

services:
  chat-bot:
    image: "node-chat-bot"
    build:
      context: ./
      dockerfile: Dockerfile
    init: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    restart: unless-stopped
